# Generated by Django 3.1.13 on 2024-02-02 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapi', '0002_auto_20240202_0618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='artist_name',
            new_name='name',
        ),
    ]
